"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = VerifyEmailScreen;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_native_1 = require("react-native");
const react_native_safe_area_context_1 = require("react-native-safe-area-context");
const useVerifyEmail_1 = require("../hooks/useVerifyEmail");
const components_1 = require("@/shared/components");
function VerifyEmailScreen() {
    const { email, isChecking, isResending, cooldownSeconds, error, resendSuccess, handleResend, handleRefresh, handleSignOut, } = (0, useVerifyEmail_1.useVerifyEmail)();
    return ((0, jsx_runtime_1.jsxs)(react_native_safe_area_context_1.SafeAreaView, { className: "flex-1 bg-zinc-950 p-6 justify-between", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-1 justify-center items-center", children: [(0, jsx_runtime_1.jsx)(react_native_1.View, { className: "absolute w-72 h-72 bg-indigo-500/10 rounded-full blur-3xl" }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 text-xs font-medium tracking-widest uppercase mb-2", children: "Registration Complete" }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-50 text-3xl font-extrabold tracking-tight mb-4 text-center", children: "Verify Your Email" }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-400 text-sm text-center max-w-[280px] leading-relaxed mb-6", children: "We've sent a verification link to your inbox. Please click the link to verify your email." }), email ? ((0, jsx_runtime_1.jsx)(react_native_1.View, { className: "bg-zinc-900 border border-zinc-800 rounded-xl px-4 py-3 mb-6", children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-300 font-semibold text-sm", children: email }) })) : null, error ? ((0, jsx_runtime_1.jsx)(react_native_1.View, { className: "bg-red-500/15 border border-red-500/30 rounded-xl p-4 mb-6 w-full max-w-sm", children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-red-400 text-sm font-medium text-center", children: error }) })) : null, resendSuccess ? ((0, jsx_runtime_1.jsx)(react_native_1.View, { className: "bg-emerald-500/15 border border-emerald-500/30 rounded-xl p-4 mb-6 w-full max-w-sm", children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-emerald-400 text-sm font-medium text-center", children: "Verification link resent successfully!" }) })) : null] }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "w-full max-w-sm mx-auto gap-4", children: [(0, jsx_runtime_1.jsx)(react_native_1.TouchableOpacity, { className: "bg-indigo-600 active:bg-indigo-700 py-4 rounded-xl items-center shadow-lg shadow-indigo-600/25", onPress: handleRefresh, disabled: isChecking, children: isChecking ? ((0, jsx_runtime_1.jsx)(components_1.InlineLoader, { label: "Checking status...", color: "#ffffff" })) : ((0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-50 font-semibold text-base", children: "I've Verified My Email" })) }), (0, jsx_runtime_1.jsx)(react_native_1.TouchableOpacity, { className: "bg-zinc-900 border border-zinc-800 active:bg-zinc-800 py-4 rounded-xl items-center", onPress: handleResend, disabled: isResending || cooldownSeconds > 0, children: isResending ? ((0, jsx_runtime_1.jsx)(react_native_1.ActivityIndicator, { size: "small", color: "#a1a1aa" })) : ((0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-400 font-semibold text-base", children: cooldownSeconds > 0
                                ? `Resend Email in ${cooldownSeconds}s`
                                : 'Resend Verification Email' })) }), (0, jsx_runtime_1.jsx)(react_native_1.TouchableOpacity, { className: "py-3 items-center", onPress: handleSignOut, children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 font-semibold text-sm", children: "Cancel & Sign Out" }) })] })] }));
}
