"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProgressPhotoCard = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = __importDefault(require("react"));
const react_native_1 = require("react-native");
exports.ProgressPhotoCard = react_1.default.memo(function ProgressPhotoCard({ photoUrl, dateFormatted, angleLabel, timeOfDayLabel, onPress, onDelete, }) {
    return ((0, jsx_runtime_1.jsxs)(react_native_1.TouchableOpacity, { activeOpacity: 0.85, onPress: onPress, disabled: !onPress, accessible: true, accessibilityRole: "button", accessibilityLabel: `Progress photo taken on ${dateFormatted}${angleLabel ? `, ${angleLabel}` : ''}`, accessibilityHint: "Tap to view full screen comparison", className: "bg-zinc-900 border border-zinc-800 rounded-2xl overflow-hidden shadow-sm", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "relative w-full h-44 bg-zinc-950", children: [(0, jsx_runtime_1.jsx)(react_native_1.Image, { source: { uri: photoUrl }, className: "w-full h-full", resizeMode: "cover", accessible: true, accessibilityLabel: `Skin photo from ${dateFormatted}` }), angleLabel ? ((0, jsx_runtime_1.jsx)(react_native_1.View, { className: "absolute top-2 left-2 bg-zinc-950/80 px-2 py-0.5 rounded-md border border-zinc-800", children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-200 text-[10px] font-semibold", children: angleLabel }) })) : null, onDelete ? ((0, jsx_runtime_1.jsx)(react_native_1.TouchableOpacity, { onPress: onDelete, accessible: true, accessibilityRole: "button", accessibilityLabel: "Delete progress photo", hitSlop: { top: 10, bottom: 10, left: 10, right: 10 }, className: "absolute top-2 right-2 bg-rose-500/20 border border-rose-500/40 w-7 h-7 rounded-full items-center justify-center", children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-rose-400 text-xs font-bold", children: "\u2715" }) })) : null] }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "p-2.5 flex-row items-center justify-between bg-zinc-900", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-300 text-xs font-medium", children: dateFormatted }), timeOfDayLabel ? ((0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 text-[10px] font-medium", children: timeOfDayLabel })) : null] })] }));
});
