"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.themeColors = exports.shadow = exports.shadows = exports.radius = exports.lineHeights = exports.fontWeights = exports.fontSizes = exports.typography = exports.spacing = exports.colors = void 0;
var colors_1 = require("./colors");
Object.defineProperty(exports, "colors", { enumerable: true, get: function () { return colors_1.colors; } });
var spacing_1 = require("./spacing");
Object.defineProperty(exports, "spacing", { enumerable: true, get: function () { return spacing_1.spacing; } });
var typography_1 = require("./typography");
Object.defineProperty(exports, "typography", { enumerable: true, get: function () { return typography_1.typography; } });
Object.defineProperty(exports, "fontSizes", { enumerable: true, get: function () { return typography_1.fontSizes; } });
Object.defineProperty(exports, "fontWeights", { enumerable: true, get: function () { return typography_1.fontWeights; } });
Object.defineProperty(exports, "lineHeights", { enumerable: true, get: function () { return typography_1.lineHeights; } });
var radius_1 = require("./radius");
Object.defineProperty(exports, "radius", { enumerable: true, get: function () { return radius_1.radius; } });
var shadows_1 = require("./shadows");
Object.defineProperty(exports, "shadows", { enumerable: true, get: function () { return shadows_1.shadows; } });
Object.defineProperty(exports, "shadow", { enumerable: true, get: function () { return shadows_1.shadow; } });
/** Composed theme object for convenient access */
var colors_2 = require("./colors");
Object.defineProperty(exports, "themeColors", { enumerable: true, get: function () { return colors_2.colors; } });
