/**
 * Intelligent Scheduling Engine
 * SelfOS v3.1.0 — Batch 14B
 */

import type { TimeBlock, CalendarEvent } from '../domain/calendar.types';
import { ScheduleSimulationEngine } from './ScheduleSimulationEngine';

export class SchedulingEngine {
  static generateSchedule(events: readonly CalendarEvent[]): TimeBlock[] {
    const blocks: TimeBlock[] = events.map((e) => ({
      id: `block_${e.id}`,
      title: e.title,
      startTime: e.startTime,
      endTime: e.endTime,
      type: e.type,
      isAutoGenerated: false,
    }));

    const simulation = ScheduleSimulationEngine.simulateCandidates(blocks);
    return [...simulation.blocks];
  }
}
export default SchedulingEngine;
