/**
 * Schedule Optimisation Engine
 * SelfOS v3.1.0 — Batch 14B
 */

import type { TimeBlock } from '../domain/calendar.types';
import { calendarEventBus } from '../events/CalendarEventBus';

export class ScheduleOptimisationEngine {
  static optimizeForHealth(blocks: readonly TimeBlock[], sleepQualityScore: number): TimeBlock[] {
    if (sleepQualityScore >= 70) return [...blocks];

    // If poor sleep quality, insert a recovery block after the first focus session
    const optimized = [...blocks];
    const firstDeepIndex = optimized.findIndex((b) => b.type === 'deep_work');

    if (firstDeepIndex >= 0) {
      const deepBlock = optimized[firstDeepIndex];
      const recoveryStart = new Date(deepBlock.endTime);
      const recoveryEnd = new Date(recoveryStart.getTime() + 30 * 60 * 1000);

      optimized.splice(firstDeepIndex + 1, 0, {
        id: `block_recovery_${Date.now()}`,
        title: 'Health Recovery & Hydration Break',
        startTime: recoveryStart,
        endTime: recoveryEnd,
        type: 'recovery',
        isAutoGenerated: true,
      });

      calendarEventBus.emit('ScheduleOptimized', { reason: 'Poor sleep recovery adjustment' });
    }

    return optimized;
  }
}
export default ScheduleOptimisationEngine;
