"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SkinWeeklyReviewCard = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_native_1 = require("react-native");
const SkinWeeklyReviewCard = function SkinWeeklyReviewCard({ review, }) {
    return ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "bg-zinc-900 border border-zinc-800 rounded-2xl p-4 gap-4 shadow-sm my-2", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center justify-between border-b border-zinc-800/80 pb-3", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 text-[10px] font-bold uppercase tracking-wider", children: "Weekly AI Analysis" }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-50 text-base font-bold", children: review.dateRange })] }), (0, jsx_runtime_1.jsx)(react_native_1.View, { className: "bg-emerald-500/10 border border-emerald-500/30 px-3 py-1 rounded-full", children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-emerald-400 text-xs font-bold", children: review.scoreChangeLabel }) })] }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-300 text-xs leading-5 bg-zinc-950 p-3 rounded-xl border border-zinc-800/60", children: review.summary }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "gap-1.5", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-emerald-400 text-xs font-bold uppercase tracking-wide", children: "Key Highlights" }), review.highlights.map((h, idx) => ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center gap-2", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-emerald-400 text-xs", children: "\u2713" }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-300 text-xs flex-1", children: h })] }, idx)))] }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "gap-1.5", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-amber-400 text-xs font-bold uppercase tracking-wide", children: "Areas of Focus" }), review.areasToImprove.map((a, idx) => ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center gap-2", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-amber-400 text-xs", children: "\uD83C\uDFAF" }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-300 text-xs flex-1", children: a })] }, idx)))] })] }));
};
exports.SkinWeeklyReviewCard = SkinWeeklyReviewCard;
