"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SkinRecommendationCard = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_native_1 = require("react-native");
const SkinRecommendationCard = function SkinRecommendationCard({ recommendation, onApply, }) {
    const confidencePct = Math.round((recommendation.confidenceScore || 0.9) * 100);
    return ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "bg-zinc-900 border border-zinc-800 rounded-2xl p-4 gap-3 shadow-sm my-1.5", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center justify-between", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center gap-2 flex-1 pr-2", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-base", children: "\uD83D\uDCA1" }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-50 font-bold text-sm flex-1", children: recommendation.title })] }), (0, jsx_runtime_1.jsx)(react_native_1.View, { className: "bg-pink-500/10 border border-pink-500/30 px-2.5 py-0.5 rounded-full", children: (0, jsx_runtime_1.jsxs)(react_native_1.Text, { className: "text-pink-400 text-[10px] font-semibold", children: [confidencePct, "% Match"] }) })] }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-400 text-xs leading-5", children: recommendation.summary }), recommendation.actionableSteps && recommendation.actionableSteps.length > 0 ? ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "bg-zinc-950/80 p-3 rounded-xl gap-1.5 border border-zinc-800/80", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-300 text-[11px] font-bold uppercase tracking-wider", children: "Actionable Steps" }), recommendation.actionableSteps.map((step, idx) => ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-start gap-2", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-pink-400 text-xs font-bold", children: "\u2022" }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-300 text-xs flex-1", children: step })] }, idx)))] })) : null, onApply ? ((0, jsx_runtime_1.jsx)(react_native_1.TouchableOpacity, { activeOpacity: 0.8, onPress: () => onApply(recommendation), className: "bg-pink-600/20 border border-pink-500/40 py-2 px-3 rounded-xl items-center justify-center mt-1", children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-pink-400 text-xs font-bold", children: "Apply Recommendation to Vanity" }) })) : null] }));
};
exports.SkinRecommendationCard = SkinRecommendationCard;
