"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ComparisonCard = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = __importDefault(require("react"));
const react_native_1 = require("react-native");
exports.ComparisonCard = react_1.default.memo(function ComparisonCard({ beforePhoto, afterPhoto, }) {
    return ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "bg-zinc-900 border border-zinc-800 rounded-2xl p-4 gap-3 shadow-md", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-400 text-xs font-semibold uppercase tracking-wider text-center", children: "Side-by-Side Growth Comparison" }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row gap-3", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-1 bg-zinc-950 border border-zinc-800 rounded-xl overflow-hidden", children: [(0, jsx_runtime_1.jsx)(react_native_1.View, { className: "bg-amber-500/20 py-1 items-center", children: (0, jsx_runtime_1.jsxs)(react_native_1.Text, { className: "text-amber-400 text-[10px] font-extrabold uppercase", children: ["BEFORE (", beforePhoto.formattedDate, ")"] }) }), (0, jsx_runtime_1.jsx)(react_native_1.View, { className: "w-full aspect-square bg-zinc-900", children: (0, jsx_runtime_1.jsx)(react_native_1.Image, { source: { uri: beforePhoto.photoUrl }, className: "w-full h-full", resizeMode: "cover" }) }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "p-2", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-300 text-[11px] font-semibold", children: beforePhoto.angleLabel }), beforePhoto.notes ? ((0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 text-[10px]", numberOfLines: 2, children: beforePhoto.notes })) : null] })] }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-1 bg-zinc-950 border border-emerald-500/40 rounded-xl overflow-hidden", children: [(0, jsx_runtime_1.jsx)(react_native_1.View, { className: "bg-emerald-500/20 py-1 items-center", children: (0, jsx_runtime_1.jsxs)(react_native_1.Text, { className: "text-emerald-400 text-[10px] font-extrabold uppercase", children: ["AFTER (", afterPhoto.formattedDate, ")"] }) }), (0, jsx_runtime_1.jsx)(react_native_1.View, { className: "w-full aspect-square bg-zinc-900", children: (0, jsx_runtime_1.jsx)(react_native_1.Image, { source: { uri: afterPhoto.photoUrl }, className: "w-full h-full", resizeMode: "cover" }) }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "p-2", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-300 text-[11px] font-semibold", children: afterPhoto.angleLabel }), afterPhoto.notes ? ((0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 text-[10px]", numberOfLines: 2, children: afterPhoto.notes })) : null] })] })] })] }));
});
