"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConditionSummaryCard = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = __importDefault(require("react"));
const react_native_1 = require("react-native");
exports.ConditionSummaryCard = react_1.default.memo(function ConditionSummaryCard({ latestCondition, onOpenHistory, onNewAssessment }) {
    return ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "bg-zinc-900 border border-zinc-800 p-4 rounded-2xl gap-3 shadow-md", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center justify-between", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-400 text-xs font-semibold uppercase tracking-wider", children: "Hair & Scalp Health Assessment" }), (0, jsx_runtime_1.jsx)(react_native_1.TouchableOpacity, { onPress: onOpenHistory, accessibilityRole: "button", children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-amber-400 text-xs font-semibold", children: "History \u2192" }) })] }), latestCondition ? ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center justify-between bg-zinc-950/80 border border-zinc-800 p-3 rounded-xl", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "gap-0.5", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center gap-2", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-100 text-base font-extrabold", children: latestCondition.scalpTypeLabel }), (0, jsx_runtime_1.jsx)(react_native_1.View, { className: `px-2 py-0.5 rounded-md border ${latestCondition.healthBadgeColor}`, children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-[10px] font-bold", children: latestCondition.healthBadgeLabel }) })] }), (0, jsx_runtime_1.jsxs)(react_native_1.Text, { className: "text-zinc-400 text-xs", children: ["Last recorded: ", latestCondition.formattedDate] })] }), (0, jsx_runtime_1.jsx)(react_native_1.TouchableOpacity, { className: "bg-amber-500 active:bg-amber-600 px-3.5 py-2 rounded-xl", onPress: onNewAssessment, accessibilityRole: "button", children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-950 font-extrabold text-xs", children: "+ Log New" }) })] })) : ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "bg-zinc-950/60 border border-dashed border-zinc-800 p-4 rounded-xl items-center gap-2", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-400 text-xs text-center", children: "No hair & scalp health assessment recorded yet." }), (0, jsx_runtime_1.jsx)(react_native_1.TouchableOpacity, { className: "bg-amber-500 active:bg-amber-600 px-4 py-2 rounded-xl", onPress: onNewAssessment, accessibilityRole: "button", children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-950 font-extrabold text-xs", children: "+ Perform First Self-Assessment" }) })] }))] }));
});
