"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.HairRoutineCard = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = __importDefault(require("react"));
const react_native_1 = require("react-native");
const routine_1 = require("@/features/routine");
exports.HairRoutineCard = react_1.default.memo(function HairRoutineCard({ routine, onLogPress, onDelete }) {
    return ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "bg-zinc-900/90 border border-zinc-800/80 p-4 rounded-2xl gap-3 shadow-md", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center justify-between", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-1 pr-2", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center gap-2 mb-0.5", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 text-[10px] font-bold uppercase tracking-wider", children: routine.categoryLabel }), (0, jsx_runtime_1.jsxs)(react_native_1.Text, { className: "text-emerald-400 text-[10px]", children: ["\uD83D\uDD25 ", routine.currentStreak, " day streak"] })] }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-100 text-base font-extrabold", numberOfLines: 1, children: routine.title })] }), (0, jsx_runtime_1.jsx)(routine_1.RoutineStatusBadge, { status: routine.status, size: "sm" })] }), routine.products.length > 0 ? ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "gap-1 bg-zinc-950/60 p-2.5 rounded-xl border border-zinc-800/60", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 text-[10px] font-bold uppercase", children: "Products Used:" }), (0, jsx_runtime_1.jsx)(react_native_1.View, { className: "flex-row flex-wrap gap-1.5 pt-0.5", children: routine.products.map((p) => ((0, jsx_runtime_1.jsx)(react_native_1.View, { className: "bg-zinc-900 border border-zinc-800 px-2 py-0.5 rounded-md", children: (0, jsx_runtime_1.jsxs)(react_native_1.Text, { className: "text-zinc-300 text-xs font-medium", children: [p.brand, " ", p.name] }) }, p.id))) })] })) : null, (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center justify-between pt-1 border-t border-zinc-800/60", children: [(0, jsx_runtime_1.jsx)(react_native_1.TouchableOpacity, { className: "bg-emerald-500/10 border border-emerald-500/30 px-3 py-1.5 rounded-lg", onPress: () => onLogPress?.(routine.id), accessibilityRole: "button", children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-emerald-400 font-bold text-xs", children: "\u2713 Log Wash Day" }) }), onDelete ? ((0, jsx_runtime_1.jsx)(react_native_1.TouchableOpacity, { onPress: () => onDelete(routine.id, routine.routineId), accessibilityRole: "button", children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-rose-500 text-xs font-semibold", children: "Delete" }) })) : null] })] }));
});
