"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.useDeleteHairCondition = exports.useUpdateHairCondition = exports.useCreateHairCondition = exports.useLatestHairCondition = exports.useHairConditions = exports.useHairTimeline = exports.useDeleteHairPhoto = exports.useUploadHairPhoto = exports.useHairPhotos = exports.useHaircareDashboard = exports.useHairLogs = exports.useHairRoutines = exports.useHairProducts = exports.haircareKeys = void 0;
var queryKeys_1 = require("./queryKeys");
Object.defineProperty(exports, "haircareKeys", { enumerable: true, get: function () { return queryKeys_1.haircareKeys; } });
var useHairProducts_1 = require("./useHairProducts");
Object.defineProperty(exports, "useHairProducts", { enumerable: true, get: function () { return useHairProducts_1.useHairProducts; } });
var useHairRoutines_1 = require("./useHairRoutines");
Object.defineProperty(exports, "useHairRoutines", { enumerable: true, get: function () { return useHairRoutines_1.useHairRoutines; } });
var useHairLogs_1 = require("./useHairLogs");
Object.defineProperty(exports, "useHairLogs", { enumerable: true, get: function () { return useHairLogs_1.useHairLogs; } });
var useHaircareDashboard_1 = require("./useHaircareDashboard");
Object.defineProperty(exports, "useHaircareDashboard", { enumerable: true, get: function () { return useHaircareDashboard_1.useHaircareDashboard; } });
var useHairPhotos_1 = require("./useHairPhotos");
Object.defineProperty(exports, "useHairPhotos", { enumerable: true, get: function () { return useHairPhotos_1.useHairPhotos; } });
var useUploadHairPhoto_1 = require("./useUploadHairPhoto");
Object.defineProperty(exports, "useUploadHairPhoto", { enumerable: true, get: function () { return useUploadHairPhoto_1.useUploadHairPhoto; } });
var useDeleteHairPhoto_1 = require("./useDeleteHairPhoto");
Object.defineProperty(exports, "useDeleteHairPhoto", { enumerable: true, get: function () { return useDeleteHairPhoto_1.useDeleteHairPhoto; } });
var useHairTimeline_1 = require("./useHairTimeline");
Object.defineProperty(exports, "useHairTimeline", { enumerable: true, get: function () { return useHairTimeline_1.useHairTimeline; } });
var useHairConditions_1 = require("./useHairConditions");
Object.defineProperty(exports, "useHairConditions", { enumerable: true, get: function () { return useHairConditions_1.useHairConditions; } });
var useLatestHairCondition_1 = require("./useLatestHairCondition");
Object.defineProperty(exports, "useLatestHairCondition", { enumerable: true, get: function () { return useLatestHairCondition_1.useLatestHairCondition; } });
var useCreateHairCondition_1 = require("./useCreateHairCondition");
Object.defineProperty(exports, "useCreateHairCondition", { enumerable: true, get: function () { return useCreateHairCondition_1.useCreateHairCondition; } });
var useUpdateHairCondition_1 = require("./useUpdateHairCondition");
Object.defineProperty(exports, "useUpdateHairCondition", { enumerable: true, get: function () { return useUpdateHairCondition_1.useUpdateHairCondition; } });
var useDeleteHairCondition_1 = require("./useDeleteHairCondition");
Object.defineProperty(exports, "useDeleteHairCondition", { enumerable: true, get: function () { return useDeleteHairCondition_1.useDeleteHairCondition; } });
