/**
 * Calendar, Time Blocking & Intelligent Scheduling Unit Tests
 * SelfOS v3.1.0 — Batch 14B
 *
 * Run with: npx tsx src/features/productivity/calendar/__tests__/calendar.test.ts
 */

import { ConflictDetectionEngine } from '../conflicts/ConflictDetectionEngine';
import { ScheduleScoreEngine } from '../scheduling/ScheduleScoreEngine';
import { ScheduleSimulationEngine } from '../scheduling/ScheduleSimulationEngine';
import { RecurrenceEngine } from '../recurrence/RecurrenceEngine';
import { AvailabilityManager } from '../availability/AvailabilityManager';
import { ScheduleOptimisationEngine } from '../scheduling/ScheduleOptimisationEngine';
import { FocusSessionEngine } from '../focus/FocusSessionEngine';
import { CalendarAnalyticsEngine } from '../analytics/CalendarAnalyticsEngine';
import type { CalendarEvent, TimeBlock } from '../domain/calendar.types';

// Test variables
let passCount = 0;
let failCount = 0;
const failures: string[] = [];

function assert(condition: boolean, message: string): void {
  if (condition) {
    passCount++;
  } else {
    failCount++;
    failures.push(`FAIL: ${message}`);
    console.error(`  ✗ ${message}`);
  }
}

function describe(name: string, fn: () => void): void {
  console.log(`\n▸ ${name}`);
  fn();
}

function it(name: string, fn: () => void): void {
  try {
    fn();
    console.log(`  ✓ ${name}`);
  } catch (error) {
    failCount++;
    const msg = error instanceof Error ? error.message : String(error);
    failures.push(`FAIL: ${name} — ${msg}`);
    console.error(`  ✗ ${name} — ${msg}`);
  }
}

// =========================================================================
// RUN TEST SCENARIOS
// =========================================================================

describe('ConflictDetectionEngine — Time Overlaps', () => {
  it('detects overlapping calendar events', () => {
    const events: CalendarEvent[] = [
      { id: 'e1', userId: 'u1', title: 'Deep Work', startTime: new Date('2026-07-28T09:00:00Z'), endTime: new Date('2026-07-28T10:30:00Z'), type: 'deep_work', isRecurring: false, color: '#FF4081' },
      { id: 'e2', userId: 'u1', title: 'Team Meeting', startTime: new Date('2026-07-28T10:00:00Z'), endTime: new Date('2026-07-28T11:00:00Z'), type: 'meeting', isRecurring: false, color: '#3F51B5' },
    ];

    const conflicts = ConflictDetectionEngine.detectConflicts(events);
    assert(conflicts.length === 1, 'Detects 1 time conflict overlap');
    assert(conflicts[0].eventId1 === 'e1' && conflicts[0].eventId2 === 'e2', 'Correct conflicting event IDs');
  });
});

describe('ScheduleScoreEngine & Simulation', () => {
  it('evaluates quality score and rewards deep work', () => {
    const blocks: TimeBlock[] = [
      { id: 'b1', title: 'Focus 1', startTime: new Date(), endTime: new Date(), type: 'deep_work', isAutoGenerated: false },
      { id: 'b2', title: 'Focus 2', startTime: new Date(), endTime: new Date(), type: 'deep_work', isAutoGenerated: false },
    ];

    const simulation = ScheduleSimulationEngine.simulateCandidates(blocks);
    assert(simulation.qualityScore === 95, `Expected quality score 95, got ${simulation.qualityScore}`);
  });
});

describe('RecurrenceEngine — Expansion', () => {
  it('expands recurring events into multiple occurrences', () => {
    const recurringEvt: CalendarEvent = {
      id: 'e_rec',
      userId: 'u1',
      title: 'Daily Standup',
      startTime: new Date('2026-07-28T09:00:00Z'),
      endTime: new Date('2026-07-28T09:15:00Z'),
      type: 'meeting',
      isRecurring: true,
      recurrenceRule: 'FREQ=DAILY',
      color: '#FF4081',
    };

    const expanded = RecurrenceEngine.expandRecurrences(recurringEvt, 5);
    assert(expanded.length === 5, 'Expands to 5 occurrence instances');
    assert(expanded[1].id === 'e_rec_occ_1', 'Occurrence has unique suffix ID');
  });
});

describe('AvailabilityManager — Profiles', () => {
  it('retrieves default work profile windows', () => {
    const prof = AvailabilityManager.getProfile('work');
    assert(prof.windows.length === 5, 'Work profile contains 5 weekday windows');
    assert(prof.quietHoursStart === 22, 'Quiet hours start at 22:00');
  });
});

describe('ScheduleOptimisationEngine — Health Adjustment', () => {
  it('inserts a recovery block when sleep quality is low (<70)', () => {
    const blocks: TimeBlock[] = [
      { id: 'b1', title: 'Focus', startTime: new Date('2026-07-28T09:00:00Z'), endTime: new Date('2026-07-28T10:30:00Z'), type: 'deep_work', isAutoGenerated: false },
    ];

    const optimized = ScheduleOptimisationEngine.optimizeForHealth(blocks, 50); // Low sleep score 50
    assert(optimized.length === 2, 'Inserts 1 recovery block into schedule');
    assert(optimized[1].type === 'recovery', 'Inserted block is type recovery');
  });
});

describe('FocusSessionEngine — Pomodoro Tracking', () => {
  it('tracks Pomodoro session start and completion', () => {
    const session = FocusSessionEngine.startSession('u1', 25);
    assert(session.status === 'active', 'Initial status is active');
    const completed = FocusSessionEngine.completeSession(session);
    assert(completed.status === 'completed', 'Completed status is completed');
    assert(completed.completedMinutes === 25, 'Completed 25 minutes');
  });
});

describe('CalendarAnalyticsEngine — Deep Work Ratios', () => {
  it('computes deep work ratio and context switches', () => {
    const start = new Date('2026-07-28T09:00:00Z');
    const endDeep = new Date('2026-07-28T11:00:00Z'); // 2 hours
    const endMeet = new Date('2026-07-28T12:00:00Z'); // 1 hour

    const blocks: TimeBlock[] = [
      { id: 'b1', title: 'Deep', startTime: start, endTime: endDeep, type: 'deep_work', isAutoGenerated: false },
      { id: 'b2', title: 'Meet', startTime: endDeep, endTime: endMeet, type: 'meeting', isAutoGenerated: false },
    ];

    const analytics = CalendarAnalyticsEngine.computeAnalytics(blocks);
    assert(analytics.scheduledHours === 3, `Expected 3 scheduled hours, got ${analytics.scheduledHours}`);
    assert(analytics.focusHours === 2, `Expected 2 focus hours, got ${analytics.focusHours}`);
    assert(analytics.deepWorkRatio === 0.67, `Expected 0.67 deep work ratio, got ${analytics.deepWorkRatio}`);
  });
});

// =========================================================================
// RESULTS
// =========================================================================
console.log('\n' + '='.repeat(60));
console.log(`Tests complete: ${passCount} passed, ${failCount} failed`);
if (failures.length > 0) {
  console.log('\nFailures:');
  failures.forEach((f) => console.log(`  ${f}`));
}
console.log('='.repeat(60));

process.exit(failCount > 0 ? 1 : 0);
