"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.NutritionWeeklyReviewCard = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = __importDefault(require("react"));
const react_native_1 = require("react-native");
exports.NutritionWeeklyReviewCard = react_1.default.memo(function NutritionWeeklyReviewCard({ review, }) {
    return ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "bg-zinc-900 border border-zinc-800 p-5 rounded-2xl shadow-sm gap-4", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center justify-between border-b border-zinc-850 pb-3", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 text-[10px] font-bold uppercase tracking-wider", children: "Weekly Review" }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-50 text-base font-extrabold tracking-tight mt-0.5", children: review.dateRange })] }), (0, jsx_runtime_1.jsx)(react_native_1.View, { className: "bg-pink-500/10 border border-pink-500/20 px-3 py-1 rounded-full", children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-pink-400 text-xs font-bold uppercase tracking-wider", children: review.scoreChangeLabel }) })] }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-300 text-xs leading-relaxed", children: review.summary }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "gap-2.5", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 text-[10px] font-bold uppercase tracking-wider", children: "Highlights:" }), review.highlights.map((highlight, idx) => ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row gap-2.5 items-start pl-1", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-emerald-400 text-xs font-bold mt-0.5", children: "\u2713" }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-300 text-xs leading-relaxed flex-1", children: highlight })] }, idx)))] }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "gap-2.5 border-t border-zinc-850 pt-3", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 text-[10px] font-bold uppercase tracking-wider", children: "Areas to Improve:" }), review.areasToImprove.map((area, idx) => ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row gap-2.5 items-start pl-1", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-amber-400 text-xs font-bold mt-0.5", children: "\u26A0" }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-300 text-xs leading-relaxed flex-1", children: area })] }, idx)))] })] }));
});
