/**
 * Schedule Template System Engine
 * SelfOS v3.1.0 — Batch 14B
 */

import type { ScheduleTemplate } from '../domain/calendar.types';

export class ScheduleTemplateEngine {
  private static readonly TEMPLATES: Record<string, ScheduleTemplate> = {
    'deep-work-heavy': {
      templateId: 'deep-work-heavy',
      name: 'Deep Work Heavy',
      description: 'Prioritizes 90-min uninterrupted focus blocks in the morning.',
      defaultBlocks: [
        { title: 'Morning Deep Work', type: 'deep_work', isAutoGenerated: true },
        { title: 'Recovery & Hydration Break', type: 'recovery', isAutoGenerated: true },
      ],
    },
    'recovery-focused': {
      templateId: 'recovery-focused',
      name: 'Recovery Focused',
      description: 'Inserts frequent breaks and reduced workload blocks.',
      defaultBlocks: [
        { title: 'Light Review', type: 'learning', isAutoGenerated: true },
        { title: 'Rest & Movement Session', type: 'exercise', isAutoGenerated: true },
      ],
    },
  };

  static getTemplate(templateId: string): ScheduleTemplate | undefined {
    return this.TEMPLATES[templateId];
  }
}
export default ScheduleTemplateEngine;
