/**
 * Time Blocking Engine
 * SelfOS v3.1.0 — Batch 14B
 */

import type { TimeBlock, TimeBlockType } from '../domain/calendar.types';

export class TimeBlockingEngine {
  static createBlock(title: string, start: Date, durationMinutes: number, type: TimeBlockType): TimeBlock {
    const end = new Date(start.getTime() + durationMinutes * 60 * 1000);
    return {
      id: `block_${Date.now()}`,
      title,
      startTime: start,
      endTime: end,
      type,
      isAutoGenerated: true,
    };
  }
}
export default TimeBlockingEngine;
