/**
 * Calendar & Intelligent Scheduling Domain Types
 * SelfOS v3.1.0 — Batch 14B
 */

export type TimeBlockType =
  | 'deep_work'
  | 'meeting'
  | 'health_routine'
  | 'exercise'
  | 'meal'
  | 'learning'
  | 'recovery'
  | 'break'
  | 'personal'
  | 'sleep_prep';

export type AvailabilityProfileType = 'work' | 'weekend' | 'travel' | 'recovery';

export interface CalendarEvent {
  readonly id: string;
  readonly userId: string;
  readonly title: string;
  readonly description?: string;
  readonly startTime: Date;
  readonly endTime: Date;
  readonly type: TimeBlockType;
  readonly isRecurring: boolean;
  readonly recurrenceRule?: string; // e.g. 'FREQ=DAILY'
  readonly color: string;
  readonly isAllDay?: boolean;
}

export interface TimeBlock {
  readonly id: string;
  readonly title: string;
  readonly startTime: Date;
  readonly endTime: Date;
  readonly type: TimeBlockType;
  readonly isAutoGenerated: boolean;
  readonly linkedTaskId?: string;
}

export interface AvailabilityWindow {
  readonly dayOfWeek: number; // 0-6 (Sun-Sat)
  readonly startHour: number;  // 0-23
  readonly endHour: number;    // 0-23
}

export interface AvailabilityProfile {
  readonly profileId: string;
  readonly name: AvailabilityProfileType;
  readonly windows: readonly AvailabilityWindow[];
  readonly quietHoursStart: number;
  readonly quietHoursEnd: number;
}

export interface FreeSlot {
  readonly start: Date;
  readonly end: Date;
  readonly durationMinutes: number;
}

export interface FocusSession {
  readonly sessionId: string;
  readonly userId: string;
  readonly durationMinutes: number;
  readonly completedMinutes: number;
  readonly distractionCount: number;
  readonly status: 'active' | 'paused' | 'completed' | 'cancelled';
  readonly startedAt: Date;
}

export interface ScheduleConflict {
  readonly conflictId: string;
  readonly eventId1: string;
  readonly eventId2: string;
  readonly reason: string;
  readonly severity: 'low' | 'medium' | 'high';
}

export interface ScheduleRecommendation {
  readonly id: string;
  readonly title: string;
  readonly suggestedStartTime: Date;
  readonly score: number;
  readonly rationale: string;
}

export interface CalendarAnalytics {
  readonly scheduledHours: number;
  readonly focusHours: number;
  readonly meetingHours: number;
  readonly recoveryHours: number;
  readonly deepWorkRatio: number; // 0-1.0
  readonly contextSwitches: number;
}

export interface ScheduleTemplate {
  readonly templateId: string;
  readonly name: string;
  readonly description: string;
  readonly defaultBlocks: readonly Omit<TimeBlock, 'id' | 'startTime' | 'endTime'>[];
}
