"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.AnalyticsSummaryWidget = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = __importDefault(require("react"));
const react_native_1 = require("react-native");
exports.AnalyticsSummaryWidget = react_1.default.memo(function AnalyticsSummaryWidget({ analytics, onOpenAnalytics }) {
    return ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "bg-zinc-900 border border-zinc-800 p-4 rounded-2xl gap-3 shadow-md", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center justify-between", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center gap-2", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-xl", children: "\uD83D\uDCCA" }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-400 text-xs font-semibold uppercase tracking-wider", children: "Haircare Insights & Analytics" })] }), (0, jsx_runtime_1.jsx)(react_native_1.TouchableOpacity, { onPress: onOpenAnalytics, accessibilityRole: "button", children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-amber-400 text-xs font-semibold", children: "View Dashboard \u2192" }) })] }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row gap-2 pt-1", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-1 bg-zinc-950/80 border border-zinc-800/80 p-3 rounded-xl items-center", children: [(0, jsx_runtime_1.jsxs)(react_native_1.Text, { className: "text-amber-400 text-lg font-black", children: [analytics.weekly.completionRate, "%"] }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-400 text-[10px] font-medium text-center", children: "Weekly Rate" })] }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-1 bg-zinc-950/80 border border-zinc-800/80 p-3 rounded-xl items-center", children: [(0, jsx_runtime_1.jsxs)(react_native_1.Text, { className: "text-amber-400 text-lg font-black", children: ["Every ", analytics.monthly.avgWashIntervalDays || 3, "d"] }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-400 text-[10px] font-medium text-center", children: "Wash Interval" })] }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-1 bg-zinc-950/80 border border-zinc-800/80 p-3 rounded-xl items-center", children: [(0, jsx_runtime_1.jsxs)(react_native_1.Text, { className: "text-emerald-400 text-lg font-black", children: [analytics.conditionTrend.avgOverallHealth, "/10"] }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-400 text-[10px] font-medium text-center", children: "Scalp Health" })] })] })] }));
});
