"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.AssessmentCard = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = __importDefault(require("react"));
const react_native_1 = require("react-native");
exports.AssessmentCard = react_1.default.memo(function AssessmentCard({ assessment, onDelete, }) {
    const handleDeleteConfirm = () => {
        react_native_1.Alert.alert('Delete Assessment', 'Are you sure you want to delete this skin assessment record?', [
            { text: 'Cancel', style: 'cancel' },
            { text: 'Delete', style: 'destructive', onPress: onDelete },
        ]);
    };
    return ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "bg-zinc-900 border border-zinc-800 p-4 rounded-2xl gap-3 shadow-sm", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center justify-between", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 text-[10px] font-bold uppercase tracking-wider", children: assessment.recordDateFormatted }), (0, jsx_runtime_1.jsxs)(react_native_1.Text, { className: "text-zinc-50 text-base font-bold", children: ["Skin Type: ", assessment.skinTypeLabel] })] }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "px-3 py-1.5 rounded-xl border items-center justify-center", style: {
                            backgroundColor: `${assessment.healthScoreBadgeColor}15`,
                            borderColor: `${assessment.healthScoreBadgeColor}40`,
                        }, children: [(0, jsx_runtime_1.jsxs)(react_native_1.Text, { className: "text-base font-extrabold", style: { color: assessment.healthScoreBadgeColor }, children: [assessment.overallHealthScore, " / 10"] }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 text-[9px] font-bold uppercase", children: "Health Score" })] })] }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row gap-2 bg-zinc-950/70 p-2.5 rounded-xl border border-zinc-800/60", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-1 items-center", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 text-[10px]", children: "Hydration" }), (0, jsx_runtime_1.jsxs)(react_native_1.Text, { className: "text-zinc-200 text-xs font-bold", children: [assessment.hydrationPercentage, "%"] })] }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-1 items-center border-x border-zinc-800", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 text-[10px]", children: "Sensitivity" }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-200 text-xs font-bold", children: assessment.sensitivityStatusLabel })] }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-1 items-center", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 text-[10px]", children: "Barrier" }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-200 text-xs font-bold", children: assessment.barrierHealthStatusLabel })] })] }), assessment.topConcernsFormatted.length > 0 ? ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "gap-1", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 text-[10px] font-semibold", children: "Active Concerns:" }), (0, jsx_runtime_1.jsx)(react_native_1.View, { className: "flex-row flex-wrap gap-1.5", children: assessment.topConcernsFormatted.map((c) => ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "bg-amber-500/10 border border-amber-500/30 px-2 py-0.5 rounded-md flex-row items-center gap-1", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-amber-400 text-xs font-semibold", children: c.label }), (0, jsx_runtime_1.jsxs)(react_native_1.Text, { className: "text-amber-500 text-[10px]", children: ["(", c.severityLabel, ")"] })] }, c.concern))) })] })) : null, onDelete ? ((0, jsx_runtime_1.jsx)(react_native_1.View, { className: "flex-row justify-end pt-1 border-t border-zinc-800/40", children: (0, jsx_runtime_1.jsx)(react_native_1.TouchableOpacity, { onPress: handleDeleteConfirm, className: "py-1 px-2", children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-rose-400 text-xs font-semibold", children: "Delete Assessment" }) }) })) : null] }));
});
