"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SkincareAnalyticsDashboardScreen = SkincareAnalyticsDashboardScreen;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_native_1 = require("react-native");
const expo_router_1 = require("expo-router");
const useSkincareAnalytics_1 = require("../analytics/hooks/useSkincareAnalytics");
const StatTile_1 = require("../../../shared/components/cards/StatTile");
const ErrorStateCard_1 = require("../../../shared/components/feedback/ErrorStateCard");
const SkeletonLoader_1 = require("../../../shared/components/loaders/SkeletonLoader");
function SkincareAnalyticsDashboardScreen() {
    const router = (0, expo_router_1.useRouter)();
    const { analyticsVM, isLoading, isError, error, refetch } = (0, useSkincareAnalytics_1.useSkincareAnalytics)();
    let trendColor = '#3b82f6';
    let trendLabel = 'Stable';
    if (analyticsVM?.skinHealthScoreTrend === 'improving') {
        trendColor = '#10b981';
        trendLabel = 'Improving ↗';
    }
    else if (analyticsVM?.skinHealthScoreTrend === 'declining') {
        trendColor = '#f43f5e';
        trendLabel = 'Declining ↘';
    }
    return ((0, jsx_runtime_1.jsx)(react_native_1.SafeAreaView, { className: "flex-1 bg-zinc-950", children: (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-1 p-4 gap-4", children: [(0, jsx_runtime_1.jsx)(react_native_1.View, { className: "flex-row items-center justify-between border-b border-zinc-800 pb-3", children: (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center gap-3", children: [(0, jsx_runtime_1.jsx)(react_native_1.TouchableOpacity, { onPress: () => router.back(), className: "p-1", children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-400 text-lg font-bold", children: "\u2190 Back" }) }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-50 text-xl font-extrabold", children: "Skincare Analytics" })] }) }), isLoading ? ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "gap-3", children: [(0, jsx_runtime_1.jsx)(SkeletonLoader_1.SkeletonLoader, { height: 100 }), (0, jsx_runtime_1.jsx)(SkeletonLoader_1.SkeletonLoader, { height: 160 })] })) : isError ? ((0, jsx_runtime_1.jsx)(ErrorStateCard_1.ErrorStateCard, { message: error?.message, onRetry: refetch })) : analyticsVM ? ((0, jsx_runtime_1.jsxs)(react_native_1.ScrollView, { contentContainerStyle: { gap: 16, paddingBottom: 32 }, showsVerticalScrollIndicator: false, refreshControl: (0, jsx_runtime_1.jsx)(react_native_1.RefreshControl, { refreshing: isLoading, onRefresh: refetch, tintColor: "#ec4899" }), children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row gap-3", children: [(0, jsx_runtime_1.jsx)(StatTile_1.StatTile, { label: "Weekly Completion", value: `${analyticsVM.weeklyCompletionRate}%`, icon: "\uD83D\uDCCA", badgeColor: "#ec4899" }), (0, jsx_runtime_1.jsx)(StatTile_1.StatTile, { label: "Consistency Score", value: `${analyticsVM.currentConsistencyScore}%`, icon: "\uD83C\uDFAF", badgeColor: "#10b981" })] }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "bg-zinc-900 border border-zinc-800 p-4 rounded-2xl gap-2 shadow-sm", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-400 text-xs font-medium", children: "Skin Health Overall Trend" }), (0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-baseline justify-between", children: [(0, jsx_runtime_1.jsxs)(react_native_1.Text, { className: "text-zinc-50 text-2xl font-black", children: ["Avg ", analyticsVM.averageSkinHealthScore, " / 10"] }), (0, jsx_runtime_1.jsx)(react_native_1.View, { className: "px-3 py-1 rounded-xl border", style: {
                                                backgroundColor: `${trendColor}20`,
                                                borderColor: `${trendColor}40`,
                                            }, children: (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-xs font-extrabold", style: { color: trendColor }, children: trendLabel }) })] })] }), analyticsVM.concernProgress.length > 0 ? ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "bg-zinc-900 border border-zinc-800 p-4 rounded-2xl gap-3 shadow-sm", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-50 text-sm font-bold", children: "Concern Progress Breakdown" }), (0, jsx_runtime_1.jsx)(react_native_1.View, { className: "gap-2", children: analyticsVM.concernProgress.map((item) => ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "bg-zinc-950 p-3 rounded-xl border border-zinc-800/60 flex-row items-center justify-between", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-200 text-xs font-bold", children: item.label }), (0, jsx_runtime_1.jsxs)(react_native_1.Text, { className: "text-zinc-500 text-[10px]", children: ["Initial Severity: ", item.initialSeverity, " \u2192 Current: ", item.currentSeverity] })] }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: `text-xs font-extrabold ${item.change > 0
                                                    ? 'text-emerald-400'
                                                    : item.change < 0
                                                        ? 'text-rose-400'
                                                        : 'text-zinc-400'}`, children: item.change > 0 ? `+${item.change} Impr.` : item.change < 0 ? `${item.change}` : 'Stable' })] }, item.concern))) })] })) : null, analyticsVM.topUsedProducts.length > 0 ? ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "bg-zinc-900 border border-zinc-800 p-4 rounded-2xl gap-2 shadow-sm", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-50 text-sm font-bold", children: "Top Applied Products" }), (0, jsx_runtime_1.jsx)(react_native_1.View, { className: "gap-2 mt-1", children: analyticsVM.topUsedProducts.map((p, idx) => ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center justify-between bg-zinc-950 p-2.5 rounded-xl border border-zinc-800/60", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center gap-2", children: [(0, jsx_runtime_1.jsx)(react_native_1.View, { className: "w-5 h-5 rounded-full bg-pink-500/20 items-center justify-center", children: (0, jsx_runtime_1.jsxs)(react_native_1.Text, { className: "text-pink-400 text-[10px] font-bold", children: ["#", idx + 1] }) }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-200 text-xs font-semibold", children: p.productName })] }), (0, jsx_runtime_1.jsxs)(react_native_1.Text, { className: "text-zinc-400 text-xs font-bold", children: [p.usageCount, " uses"] })] }, p.productId))) })] })) : null, analyticsVM.insights.length > 0 ? ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "gap-2", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-50 text-sm font-bold", children: "Rule-Based Insights" }), analyticsVM.insights.map((ins) => ((0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "bg-zinc-900 border border-zinc-800 p-3.5 rounded-2xl gap-1 shadow-sm", children: [(0, jsx_runtime_1.jsxs)(react_native_1.View, { className: "flex-row items-center justify-between", children: [(0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-pink-400 text-xs font-bold", children: ins.title }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-500 text-[10px]", children: ins.category })] }), (0, jsx_runtime_1.jsx)(react_native_1.Text, { className: "text-zinc-300 text-xs leading-relaxed", children: ins.description })] }, ins.id)))] })) : null] })) : null] }) }));
}
